version: "3.9"
services:
  nginx:
    image: week2docker
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
  db:
    image: postgres
    environment:
      - POSTGRES_DB=thanhlm
      - POSTGRES_USER=thanhlm
      - POSTGRES_PASSWORD=thanhlm
