version: '3.4'

services:
  web1:
    image: web1
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:9999 --nothreading --noreload"]
    ports:
      - 9999:9999
      - 5678:5678
